//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanglaMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int SNO { get; set; }
        public int Roll { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> Mid_1 { get; set; }
        public Nullable<int> Mid_2 { get; set; }
        public Nullable<int> Final { get; set; }
        public Nullable<int> Total { get; set; }
        public int ID { get; set; }
    }
}
